language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_install:
  - nvm install lts/dubnium
install:
  - cargo build
  - npm ci
  - npm install --no-save worker-plugin@3.2
script:
  - npm run test:wasm
  - npm run start-ci
  - npm run test:js-lib